spring.application.name=EcommerceBackend
spring.datasource.url=postgresql://postgres.xhunxfypmwadnhkbwcip:Admin%401234.-@aws-1-eu-west-1.pooler.supabase.com:6543/postgres
#spring.datasource.username=supabase_admin
spring.datasource.password=Admin%401234.-
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.servlet.multipart.max-file-size=50MB
server.port=8080
