spring.application.name=EcommerceBackend

# 1. Utilisation du port 6543 avec le mode session explicite
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0

# 2. Identifiants (Vérifie bien que l'ID projet est présent dans le username)
spring.datasource.username=postgres.xhunxfypmwadnhkbwcip
spring.datasource.password=Admin@1234.-
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Hibernate - Forcer le dialecte pour éviter l'erreur de metadata
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# 4. Paramètres de pool Hikari (pour stabiliser la connexion au pooler Supabase)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000